/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
  ******************************************************************************
  Call of tuner sequence in main function.
*/

#include "led.h"
#include "delay.h"
#include "uart_driver.h"
#include <inttypes.h>
#include <stdio.h>

#define F_CPU 16000000UL

enum State {IDLE, BUSY, COLLISION};

enum State currentState = IDLE;
/*
 * E1: Any signal bus voltage edge
 * E2: Timer timeout when bus is logic-0
 * E3: Timer timeout when bus is logic-1
 * IDLE -> BUSY (E1)
 * BUSY -> COLLISION (E2)
 * BUSY -> IDLE (E3)
 * COLLISION -> BUSY (E1)
 */

int main(void)
{
	//Set up uart connection
	init_usart2(57600, F_CPU);
	//Test to to ensure connection
	printf("CE4951 Networking Project");
	//Initialize leds
	led_init();
	while(1){
		switch (currentState)
		{
		case IDLE:
			//Left two LEDs on
			led_allOff();
			led_on(9);
			led_on(8);
			// Interrupt when E1

			break;

		case BUSY:
			//Middle two LEDs on
			led_allOff();
			led_on(5);
			led_on(4);
			//Interrupt when E2

			//Interrupt when E3

			break;

		case COLLISION:
			//Right two LEDs on
			led_allOff();
			led_on(1);
			led_on(0);
			//Interrupt when E1

			break;

		default:
			led_allOff();
			//Unexpected value for currentState
			//Resetting currentState to initial value
			currentState = IDLE;

			break;
		}
	}
}
